name: fedcsis24-llm-textcat
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - conda-pack=0.7.1
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.10.13
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - accelerate==0.26.1
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.1.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.13.1
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - blis==0.7.11
      - catalogue==2.0.10
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.16.0
      - comm==0.2.0
      - confection==0.1.4
      - contourpy==1.2.0
      - cycler==0.12.1
      - cymem==2.0.8
      - dataclasses-json==0.6.4
      - datasets==2.15.0
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.7
      - et-xmlfile==1.1.0
      - evaluate==0.4.1
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastjsonschema==2.19.0
      - filelock==3.13.1
      - fonttools==4.46.0
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - httpx-sse==0.4.0
      - huggingface-hub==0.19.4
      - idna==3.6
      - ipykernel==6.27.1
      - ipython==8.18.1
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - jupyter==1.0.0
      - jupyter-client==8.6.0
      - jupyter-console==6.6.3
      - jupyter-core==5.5.0
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.1
      - jupyter-server==2.11.2
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.2
      - jupyterlab-widgets==3.0.9
      - kaleido==0.2.1
      - kiwisolver==1.4.5
      - langchain==0.1.16
      - langchain-community==0.0.33
      - langchain-core==0.1.43
      - langchain-text-splitters==0.0.1
      - langcodes==3.3.0
      - langsmith==0.1.48
      - markupsafe==2.1.3
      - marshmallow==3.21.1
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - murmurhash==1.0.10
      - mypy-extensions==1.0.0
      - nbclient==0.9.0
      - nbconvert==7.12.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.2.1
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - ollama==0.1.8
      - openpyxl==3.1.2
      - orjson==3.10.1
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.1.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.9.0
      - pillow==10.1.0
      - platformdirs==4.1.0
      - plotly==5.18.0
      - preshed==3.0.9
      - prometheus-client==0.19.0
      - prompt-toolkit==3.0.41
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==14.0.1
      - pyarrow-hotfix==0.6
      - pycparser==2.21
      - pydantic==2.5.2
      - pydantic-core==2.14.5
      - pygments==2.17.2
      - pymupdf==1.24.2
      - pymupdfb==1.24.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - referencing==0.31.1
      - regex==2023.10.3
      - requests==2.31.0
      - responses==0.18.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.13.2
      - safetensors==0.4.1
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - send2trash==1.8.2
      - six==1.16.0
      - smart-open==6.4.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - spacy==3.7.2
      - spacy-alignments==0.9.1
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - spacy-transformers==1.3.3
      - sqlalchemy==2.0.29
      - srsly==2.4.8
      - stack-data==0.6.3
      - sympy==1.12
      - tenacity==8.2.3
      - terminado==0.18.0
      - thinc==8.2.1
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - tokenizers==0.15.2
      - tomli==2.0.1
      - torch==2.1.1
      - tornado==6.4
      - tqdm==4.66.1
      - traitlets==5.14.0
      - transformers==4.35.2
      - triton==2.1.0
      - typer==0.9.0
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.8.0
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==2.1.0
      - wasabi==1.1.2
      - wcwidth==0.2.12
      - weasel==0.3.4
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - widgetsnbextension==4.0.9
      - xxhash==3.4.1
      - yarl==1.9.3
